---
name: Release

"on":
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Perform a dry run (don't create release)"
        required: false
        default: false
        type: boolean
  workflow_run:
    workflows: ["Code Quality and Build"]
    types: [completed]
    branches: [main]

jobs:
  determine-version:
    runs-on: ubuntu-latest
    # Only run if CI workflow succeeded or if manually triggered
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    outputs:
      version: ${{ steps.semver.outputs.version }}
      tag: ${{ steps.semver.outputs.tag }}
      version_tag: ${{ steps.semver.outputs.version_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for conventional commits

      - name: Determine next version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:|feat!:|fix!:"
          minor_pattern: "feat:"
          patch_pattern: "fix:|perf:"
          version_format: "${major}.${minor}.${patch}"
          search_commit_body: true
          user_format_type: "csv"

      - name: Show determined version
        run: |
          echo "Determined version: ${{ steps.semver.outputs.version }}"
          echo "Tag: ${{ steps.semver.outputs.tag }}"
          echo "Version tag: ${{ steps.semver.outputs.version_tag }}"
          echo "All outputs:"
          echo "  version: '${{ steps.semver.outputs.version }}'"
          echo "  tag: '${{ steps.semver.outputs.tag }}'"
          echo "  version_tag: '${{ steps.semver.outputs.version_tag }}'"
          echo "  increment: '${{ steps.semver.outputs.increment }}'"

  build-release:
    needs: determine-version
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            make_target: build-linux
            artifacts: "dist/*linux*"
          - os: ubuntu-latest
            name: windows
            make_target: build-windows
            artifacts: "dist/*windows*"
          - os: macos-latest
            name: macos
            make_target: build-darwin-app
            artifacts: |
              dist/*darwin*
              dist/K8s*.app/**

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.23.4"
          cache: true

      - name: Install cross-compilation dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-mingw-w64-x86-64 \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu

      - name: Build for ${{ matrix.name }}
        run: make ${{ matrix.make_target }}

      - name: List artifacts
        run: ls -la dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: k8s-tray-${{ matrix.name }}
          path: ${{ matrix.artifacts }}

  create-release:
    needs: [determine-version, build-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Prepare release assets
        run: |
          mkdir -p release

          # Copy all built binaries to release directory, excluding generic names
          find artifacts -type f \( -name "k8s-tray-*" -o -name "*.exe" \) \
            -not -name "k8s-tray" \
            -exec cp {} release/ \;

          # Handle macOS app bundle separately
          if [ -d "artifacts/k8s-tray-macos" ]; then
            cd artifacts/k8s-tray-macos

            # First, look for app bundle in dist directory
            if [ -d "dist" ] && ls dist/K8s*.app >/dev/null 2>&1; then
              zip -r ../../release/k8s-tray-macos-app.zip dist/K8s*.app
              # Copy other macOS binaries from dist, excluding generic names
              find dist -name "*darwin*" -type f -not -name "k8s-tray" -exec cp {} ../../release/ \;
            # If no dist directory, look for app bundle in current directory
            elif ls K8s*.app >/dev/null 2>&1; then
              zip -r ../../release/k8s-tray-macos-app.zip K8s*.app
              # Copy other macOS binaries from current directory, excluding generic names
              find . -name "*darwin*" -type f -not -name "k8s-tray" -exec cp {} ../../release/ \;
            # If still no app bundle found, check if there are any .app directories
            elif find . -name "*.app" -type d | head -1 >/dev/null 2>&1; then
              find . -name "*.app" -type d -exec zip -r ../../release/k8s-tray-macos-app.zip {} \;
              # Copy other macOS binaries, excluding generic names
              find . -name "*darwin*" -type f -not -name "k8s-tray" -exec cp {} ../../release/ \;
            else
              echo "No macOS app bundle found"
              # Still copy other macOS binaries, excluding generic names
              find . -name "*darwin*" -type f -not -name "k8s-tray" -exec cp {} ../../release/ \;
            fi

            cd ../..
          fi

          echo "=== Release directory contents ==="
          ls -la release/

      - name: Create checksums
        run: |
          cd release
          # Only create checksums for files, not directories
          find . -type f -not -name "checksums.txt" -exec sha256sum {} \; > checksums.txt
          echo "=== Checksums ==="
          cat checksums.txt

      - name: Create and push tag
        if: ${{ !github.event.inputs.dry_run }}
        run: |
          echo "Debug: Version from needs: ${{ needs.determine-version.outputs.version }}"
          echo "Debug: Tag from needs: ${{ needs.determine-version.outputs.tag }}"

          # Set the tag variable with fallback
          TAG="${{ needs.determine-version.outputs.tag }}"
          if [ -z "$TAG" ]; then
            TAG="v${{ needs.determine-version.outputs.version }}"
          fi

          echo "Using tag: $TAG"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$TAG" -m "Release ${{ needs.determine-version.outputs.version }}"
          git push origin "$TAG"

      - name: Create GitHub Release
        if: ${{ !github.event.inputs.dry_run }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.determine-version.outputs.tag || format('v{0}', needs.determine-version.outputs.version) }}
          name: Release ${{ needs.determine-version.outputs.version }}
          files: |
            release/*
          generate_release_notes: true
          draft: false
          prerelease: >-
            ${{
              contains(needs.determine-version.outputs.tag, 'rc') ||
              contains(needs.determine-version.outputs.tag, 'beta') ||
              contains(needs.determine-version.outputs.tag, 'alpha')
            }}
          body: |
            ## Release ${{ needs.determine-version.outputs.version }}

            ### Downloads
            - **Linux**: `k8s-tray-linux-amd64`, `k8s-tray-linux-arm64`
            - **macOS**: `k8s-tray-darwin-amd64`, `k8s-tray-darwin-arm64`,
              `k8s-tray-darwin-universal`, `k8s-tray-macos-app.zip`
            - **Windows**: `k8s-tray-windows-amd64.exe`,
              `k8s-tray-windows-arm64.exe`

            ### Verification
            Use the included `checksums.txt` to verify download integrity:
            ```bash
            sha256sum -c checksums.txt
            ```

            ### Installation
            1. Download the appropriate binary for your platform
            2. Make it executable (Linux/macOS): `chmod +x k8s-tray-*`
            3. Run the binary or install the app bundle (macOS)
